package us.wirsing.drivechain.blockchain;

public enum Status {
	OK,
	INVALID_TRANSACTION,
	DUPLICATE_TRANSACTION_UNCONFIRMED,
	DUPLICATE_TRANSACTION_BLOCKCHAIN,
	INVALID_BLOCK,
	DUPLICATE_BLOCK,
	MISSING_PREDECESSOR
}
